/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseCheckRouteImport } from './routes/supabase-check'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as DashboardSeoRouteImport } from './routes/dashboard.seo'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'
import { Route as DashboardOrcamentosRouteImport } from './routes/dashboard.orcamentos'
import { Route as DashboardMidiaRouteImport } from './routes/dashboard.midia'
import { Route as DashboardDesempenhoRouteImport } from './routes/dashboard.desempenho'
import { Route as DashboardDebugRouteImport } from './routes/dashboard.debug'
import { Route as DashboardCrmRouteImport } from './routes/dashboard.crm'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const SupabaseCheckRoute = SupabaseCheckRouteImport.update({
  id: '/supabase-check',
  path: '/supabase-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeoRoute = DashboardSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrcamentosRoute = DashboardOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMidiaRoute = DashboardMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDesempenhoRoute = DashboardDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebugRoute = DashboardDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/catalogo': typeof CatalogoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/orcamento': typeof OrcamentoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-check': typeof SupabaseCheckRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/debug': typeof DashboardDebugRoute
  '/dashboard/desempenho': typeof DashboardDesempenhoRoute
  '/dashboard/midia': typeof DashboardMidiaRoute
  '/dashboard/orcamentos': typeof DashboardOrcamentosRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/catalogo': typeof CatalogoRoute
  '/health': typeof HealthRoute
  '/orcamento': typeof OrcamentoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-check': typeof SupabaseCheckRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/debug': typeof DashboardDebugRoute
  '/dashboard/desempenho': typeof DashboardDesempenhoRoute
  '/dashboard/midia': typeof DashboardMidiaRoute
  '/dashboard/orcamentos': typeof DashboardOrcamentosRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/catalogo': typeof CatalogoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/orcamento': typeof OrcamentoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-check': typeof SupabaseCheckRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/debug': typeof DashboardDebugRoute
  '/dashboard/desempenho': typeof DashboardDesempenhoRoute
  '/dashboard/midia': typeof DashboardMidiaRoute
  '/dashboard/orcamentos': typeof DashboardOrcamentosRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/catalogo'
    | '/dashboard'
    | '/health'
    | '/orcamento'
    | '/sitemap.xml'
    | '/supabase-check'
    | '/categoria/$slug'
    | '/dashboard/configuracoes'
    | '/dashboard/crm'
    | '/dashboard/debug'
    | '/dashboard/desempenho'
    | '/dashboard/midia'
    | '/dashboard/orcamentos'
    | '/dashboard/produtos'
    | '/dashboard/seo'
    | '/produto/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/catalogo'
    | '/health'
    | '/orcamento'
    | '/sitemap.xml'
    | '/supabase-check'
    | '/categoria/$slug'
    | '/dashboard/configuracoes'
    | '/dashboard/crm'
    | '/dashboard/debug'
    | '/dashboard/desempenho'
    | '/dashboard/midia'
    | '/dashboard/orcamentos'
    | '/dashboard/produtos'
    | '/dashboard/seo'
    | '/produto/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/busca'
    | '/catalogo'
    | '/dashboard'
    | '/health'
    | '/orcamento'
    | '/sitemap.xml'
    | '/supabase-check'
    | '/categoria/$slug'
    | '/dashboard/configuracoes'
    | '/dashboard/crm'
    | '/dashboard/debug'
    | '/dashboard/desempenho'
    | '/dashboard/midia'
    | '/dashboard/orcamentos'
    | '/dashboard/produtos'
    | '/dashboard/seo'
    | '/produto/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  CatalogoRoute: typeof CatalogoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HealthRoute: typeof HealthRoute
  OrcamentoRoute: typeof OrcamentoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupabaseCheckRoute: typeof SupabaseCheckRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase-check': {
      id: '/supabase-check'
      path: '/supabase-check'
      fullPath: '/supabase-check'
      preLoaderRoute: typeof SupabaseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seo': {
      id: '/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof DashboardSeoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orcamentos': {
      id: '/dashboard/orcamentos'
      path: '/orcamentos'
      fullPath: '/dashboard/orcamentos'
      preLoaderRoute: typeof DashboardOrcamentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/midia': {
      id: '/dashboard/midia'
      path: '/midia'
      fullPath: '/dashboard/midia'
      preLoaderRoute: typeof DashboardMidiaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/desempenho': {
      id: '/dashboard/desempenho'
      path: '/desempenho'
      fullPath: '/dashboard/desempenho'
      preLoaderRoute: typeof DashboardDesempenhoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debug': {
      id: '/dashboard/debug'
      path: '/debug'
      fullPath: '/dashboard/debug'
      preLoaderRoute: typeof DashboardDebugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardDebugRoute: typeof DashboardDebugRoute
  DashboardDesempenhoRoute: typeof DashboardDesempenhoRoute
  DashboardMidiaRoute: typeof DashboardMidiaRoute
  DashboardOrcamentosRoute: typeof DashboardOrcamentosRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardSeoRoute: typeof DashboardSeoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardDebugRoute: DashboardDebugRoute,
  DashboardDesempenhoRoute: DashboardDesempenhoRoute,
  DashboardMidiaRoute: DashboardMidiaRoute,
  DashboardOrcamentosRoute: DashboardOrcamentosRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardSeoRoute: DashboardSeoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  CatalogoRoute: CatalogoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HealthRoute: HealthRoute,
  OrcamentoRoute: OrcamentoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupabaseCheckRoute: SupabaseCheckRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
